<?php
session_name("imaud_activo");
session_start();
header("Pragma: public");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: private",false);
//session_cache_limiter('private, must-revalidate');
include_once'config_rpt.php';
if(array_key_exists("consultar",$_REQUEST)){
$orientacion="P";
   if(array_key_exists("buscar",$_REQUEST)){
   	include_once'../clases/managerBD.class.php';
	include_once("../clases/Solicitudes.class.php");
	include_once("../clases/funciones.php");
	include_once("../clases/Write_PDF.php");
	$ObjmanagerBD=new managerBD('mysql');
	$ObjmanagerBD->acpw_conectar('localhost','root','','imaudbd');
	$obj_solicitud = new Solicitud($_SESSION['id_user']);
	$desc_solicitud='';
	$solicitud=(int) $_REQUEST["buscar"];
	$obj_solicitud->setId_solicitud($solicitud);
	$ObjmanagerBD->acpw_query($obj_solicitud->view_Solicitud());
	$Title_Principal="Solicitud de ";
	if($ObjmanagerBD->getResultquery()){
	$obj_solicitud->load_Solicitud($ObjmanagerBD->acpw_fetch_array());
		if($ObjmanagerBD->acpw_num_rows()>1){

		}elseif($ObjmanagerBD->acpw_num_rows()==1){
		$ObjmanagerBD->acpw_query($obj_solicitud->Obj_TipoSolicitud->view_Tip_Solic());
			if($ObjmanagerBD->getResultquery())
				if($ObjmanagerBD->acpw_num_rows()==1){
				$obj_solicitud->Obj_TipoSolicitud->load_Tip_Solic($ObjmanagerBD->acpw_fetch_array());
				$desc_solicitud=$obj_solicitud->Obj_TipoSolicitud->getDescTipo();
			}//End if:Line31
			switch($desc_solicitud){
			case 'Fiscalizacion':
			$page='1';
			include_once'../clases/Fiscalizacion.class.php';
			$orientacion="P";
			$datosfiscalizar=new Fiscalizaciones($_SESSION['id_user']);
			$datosfiscalizar->Obj_Solicitud->setId_solicitud($obj_solicitud->getId_solicitud());
			$ObjmanagerBD->acpw_query($datosfiscalizar->view_Fiscalizacion());
			if($ObjmanagerBD->acpw_num_rows()>0){
				$datosfiscalizar->load_Fiscalizacion($ObjmanagerBD->acpw_fetch_array());
			}
			break;	
			case 'Levantamiento Catastral':
			include_once'../clases/levcatastral.class.php';
			$page='2';
			$datosfiscalizar=new LevantamientoCatastral($_SESSION['id_user']);
			$datosfiscalizar->Solicitud->setId_solicitud($obj_solicitud->getId_solicitud());
			$ObjmanagerBD->acpw_query($datosfiscalizar->view_lev_catastral());
			if($ObjmanagerBD->acpw_num_rows()>0)
				$datosfiscalizar->load_lev_catastral($ObjmanagerBD->acpw_fetch_array());			
			break;
			default:
			$page=NULL;
			}//End Switch:Line 35
		}//End ifelse:Line26
	}//End if:Line 24
}//End if:Line 9
}//End if:Line 8
				
$pdf=new PDF($orientacion,'mm','Letter');
$pdf->SetPathLogo($cfg_rpt['logo_imagen']);
$pdf->Setancho_imagen($cfg_rpt['alto_imagen']);
$pdf->Setalto_imagen($cfg_rpt['ancho_imagen']);
$pdf->Setimagen_position_x($cfg_rpt['position_x']);
$pdf->Setimagen_position_y($cfg_rpt['position_y']);
$pdf->setAuthor($cfg_rpt['autor']);
$pdf->setDisplayMode('real');
$pdf->setTitle("Reporte de Fiscalizacion");
$pdf->SetMargins(3,2,3);
$pdf->AliasNbPages('Total_page');
$pdf->AddPage();
$pdf->SetFont('Arial','B',11.5);
$pdf->Cell(0,0,$Title_Principal.$desc_solicitud,0,0,'C');
$pdf->Ln(3);
if(isset($orientacion)){
	if($orientacion=='P'){
	$new_line=6;
	$pdf->Cell(150);
	$pdf->Cell(0,0,'Solicitud N: '.str_pad($obj_solicitud->getId_solicitud(),10,"0",STR_PAD_LEFT),0,1,'L');
	$pdf->Ln(10);
	$pdf->Cell(10);
//	$pdf->Cell(0,0,'Estatus: '.$obj_solicitud->getStatus(),0,0,'L');
	$pdf->Cell(21,6,"Estatus: ",0,0,'L');
	$pdf->Cell(4,4,'',1,0,'L',1);
	$pdf->SetFont('Arial','B',8);
	$pdf->Cell(20,6,"EN PROCESO",0,0,'L');
	$relleno=($obj_solicitud->getStatus()=="REALIZADA" || $obj_solicitud->getStatus()=="ACTUALIZADA")?1:0;
	$pdf->Cell(4,4,'',1,0,'L',$relleno);
	$pdf->Cell(18,6,"REALIZADA",0,0,'L');
	$relleno=($obj_solicitud->getStatus()=="ACTUALIZADA")?1:0;
	$pdf->Cell(4,4,'',1,0,'L',$relleno);
	$pdf->Cell(30,6,"ACTUALIZADA",0,0,'L');
		if(trim($obj_solicitud->getStatus())!="EN PROCESO"){
		$numerolcorf=($desc_solicitud=='Fiscalizacion')?$datosfiscalizar->getId_fiscalizacion():	$datosfiscalizar->getId_lev_catastral();
		$pdf->SetFont('','',12);
		$pdf->Cell(62,6,'N de '.$desc_solicitud.": ",0,0,'R');
		$pdf->SetFont('','B',12);
		$pdf->Cell(27,6,str_pad($numerolcorf,10,"0",STR_PAD_LEFT),0,0,'L');
		}
	$pdf->Ln($new_line+2);
	$margen_izqu=10;
	$pdf->SetFont('','',12);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(0,0,'Fecha de Solicitud:',0,1,'L');
	$pdf->Cell(50);
	$pdf->SetFont('','');
	$conver_date=new date_convert($obj_solicitud->getFecha_solicitud());
	$pdf->Cell(0,0,$conver_date->getDate(),0,1,'L');
		if(trim($obj_solicitud->getStatus())!="EN PROCESO"){
			$pdf->Cell(110);
			$pdf->SetFont('','');
			$pdf->Cell(0,0,"Fecha de ".$desc_solicitud.':',0,1,'L');
			$pdf->Cell(176);
			$pdf->SetFont('','');
			$datelcorf=($desc_solicitud=='Fiscalizacion')?$datosfiscalizar->getFecha_fiscalizacion():$datosfiscalizar->getFec_lev_catastral();
			$conver_date->setDate($datelcorf);
			$pdf->Cell(0,0,$conver_date->getDate(),0,1,'L');
		}
	$pdf->Ln($new_line);
	if($page=='1'){
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(20,6,"Usuario:",'LTB',0,'L');
			$pdf->SetFont('','');
			$ObjmanagerBD->acpw_query($datosfiscalizar->Obj_Solicitud->infCuentasClientes());
			if($ObjmanagerBD->acpw_num_rows()>0)
			$datosfiscalizar->Obj_Solicitud->load_Infctas($ObjmanagerBD->acpw_fetch_array());
			$pdf->Cell(170,6,$datosfiscalizar->Obj_Solicitud->getNombre_razon_social(),'TRB',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(28,6,"No. Cuenta:",'1',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(162,6,$datosfiscalizar->Obj_Solicitud->getNum_cta_electrica(),'1',0,'L');	
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(42,6,"Persona Solicitante:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(148,6,$datosfiscalizar->Obj_Solicitud->solicitante->getNombre(),'TBR',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(35,6,"Direccion:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(155,6,$datosfiscalizar->Obj_Solicitud->getDireccion_inmueble(),'TBR',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(28,6,"Telefono:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(162,6,$datosfiscalizar->Obj_Solicitud->solicitante->getTelefono(),'TBR',0,'L');
			$pdf->Ln($new_line+$new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(20.5,6,"Manzana:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(27,6,$datosfiscalizar->getCatas_manzana(),'TBR',0,'L');
			$pdf->SetFont('','B',12);
			$pdf->Cell(12.5,6,"Lado:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(35,6,$datosfiscalizar->getCatas_lado(),'TBR',0,'L');
			$pdf->SetFont('','B',12);
			$pdf->Cell(14.5,6,"Portal:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(33,6,$datosfiscalizar->getCatas_portal(),'TBR',0,'L');
			$pdf->SetFont('','B',12);
			$pdf->Cell(18.5,6,"Usuario:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(29,6,$datosfiscalizar->getCatas_usuario(),'TBR',0,'L');
			$pdf->Ln($new_line+$new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(28,6,"Atendido por:",'LTB',0,'L');
			$pdf->SetFont('','');
		    $ObjmanagerBD->acpw_query($datosfiscalizar->Obj_Solicitud->empleado->findEmpleado());
			if($ObjmanagerBD->acpw_num_rows()>0)
			$datosfiscalizar->Obj_Solicitud->empleado->loadEmpleado_s($ObjmanagerBD->acpw_fetch_array());
			$pdf->Cell(162,6,$datosfiscalizar->Obj_Solicitud->empleado->getApellido().', '.$datosfiscalizar->Obj_Solicitud->empleado->getNombre(),'TBR',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B',12);
			$pdf->Cell(37,6,"Tipo de Solicitud:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(153,6,$desc_solicitud,'TBR',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(190,6,"Motivo:",'LRT',1,'L');
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','');
			$pdf->MultiCell(190,6,$datosfiscalizar->Obj_Solicitud->getMotivo(),'LRB');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(190,6,"Comercial",0,0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(24,6,"Area Total",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(30,6,$datosfiscalizar->getArea_total(),'RTB',0,'L');
			$pdf->SetFont('','B');
			$pdf->Cell(24,6,"Area Util",'TB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(30,6,$datosfiscalizar->getArea_util(),'TBR',0,'L');
			$pdf->SetFont('','B');
			$pdf->Cell(35,6,"No. Empleado",'TB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(10,6,$datosfiscalizar->getNumero_empleado(),'TBR',0,'L');
			$pdf->SetFont('','B');
			$pdf->Cell(20,6,'A_os','TB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(17,6,'','TBR',1,'L');
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(95,6,"Actividad :",'LT',0,'L');
			$pdf->Cell(95,6,"Descripcion :",'RT',1,'L');
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','');
			
			$pdf->Cell(95,5,$datosfiscalizar->actividad->getId_categoria(),'BL',0,'L');
			$pdf->Cell(95,5,$datosfiscalizar->actividad->getId_actividad_econom(),'BR',0,'L');
			$pdf->Ln($new_line);
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(190,6,"Residencial",0,0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(25,6,"Tipo Casa:",'LTB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(70,6,$datosfiscalizar->vivienda->getId_tip_viviendas(),'RTB',0,'L');
			$pdf->SetFont('','B');
			$pdf->Cell(35,6,"Apartamento:",'TB',0,'L');
			$pdf->SetFont('','');
			$pdf->Cell(60,6,$datosfiscalizar->vivienda->getId_clasif_vivienda(),'TBR',1,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(190,6,"Observacion:",'LTR',1,'L');
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','');
			$pdf->Cell(190,6,$datosfiscalizar->getObservacion(),'RLB',0,'L');
			$pdf->Ln($new_line);
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','B');
			$pdf->Cell(190,6,"Resolucion:",'LTR',1,'L');
			$pdf->Cell($margen_izqu);
			$pdf->SetFont('','');
			$pdf->Cell(190,6,$datosfiscalizar->getResolucion(),'RLB',0,'L');
			$pdf->Ln($new_line*5);
			$pdf->Cell($margen_izqu);
			$pdf->Cell(95,6,"Firma y Sello del usuario",0,0,'C');
			$pdf->Cell(95,6,"Firma del Supervisor",0,0,'C');
		}elseif($page=='2'){
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','B');
		$pdf->Cell(50,6,'Parroquia','LTRB',0,'C');
		$pdf->Cell(40,6,'Urbanizacion','LTRB',0,'C');
		$pdf->Cell(50,6,'Sector','LTRB',0,'C');
		$pdf->Cell(10,6,'N','LTRB',0,'C');
		$pdf->Cell(10,6,'M','LTRB',0,'C');
		$pdf->Cell(10,6,'L',1,0,'C');
		$pdf->Cell(10,6,'P',1,0,'C');
		$pdf->Cell(10,6,'U',1,0,'C');
		$pdf->Ln($new_line);
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','');
		$ObjmanagerBD->acpw_query($datosfiscalizar->parroquia->view_Parroquia());
			if($ObjmanagerBD->acpw_num_rows()>0){
				$datosfiscalizar->parroquia->load_Parroquia($ObjmanagerBD->acpw_fetch_array());
			}
		$pdf->Cell(50,6,$datosfiscalizar->parroquia->getNombre(),1,0,'C');
		$pdf->Cell(40,6,'',1,0,'C');
		$pdf->Cell(50,6,'',1,0,'C');
		$pdf->Cell(10,6,'',1,0,'C');
		$pdf->Cell(10,6,$datosfiscalizar->getCatas_manzana(),1,0,'C');
		$pdf->Cell(10,6,$datosfiscalizar->getCatas_lado(),1,0,'C');
		$pdf->Cell(10,6,$datosfiscalizar->getCatas_portal(),1,0,'C');
		$pdf->Cell(10,6,$datosfiscalizar->getCatas_usuario(),1,0,'C');
		$pdf->Ln($new_line);
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','B');
		$pdf->Cell(50,6,"Nombre o Razon Social:",'LTB',0,'L');
		$pdf->SetFont('','');
		$pdf->Cell(140,6,$datosfiscalizar->getNombre_razon_social(),'TRB',0,'L');
		$pdf->Ln($new_line);
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','B');
		$pdf->Cell(46,6,"Representante Legal:",'LTB',0,'L');
		$pdf->SetFont('','');
		$pdf->Cell(144,6,$datosfiscalizar->representante->getNombre(),'TRB',0,'L');	
		$pdf->Ln($new_line);
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','B');
		$pdf->Cell(35,6,"Direccion Fiscal:",'LTB',0,'L');
		$pdf->SetFont('','');
		$pdf->Cell(155,6,$datosfiscalizar->getDireccion_fiscal(),'TRB',0,'L');
		$pdf->Ln($new_line);
		$pdf->Cell($margen_izqu);
		$pdf->SetFont('','B');
		$dir_inmueble=(is_null($datosfiscalizar->getDireccion_inmueble()))? $obj_solicitud->getDireccion_inmueble():$datosfiscalizar->getDireccion_inmueble();
	$pdf->Cell(50,6,"Direccion del Inmueble:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(140,6,$dir_inmueble,'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(42,6,"Direccion de Cobro:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(148,6,$datosfiscalizar->getDireccion_cobro(),'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(50,6,'Telefono',1,0,'C');
	$pdf->Cell(50,6,'R.I.F.',1,0,'C');
	$pdf->Cell(50,6,'N.I.T.',1,0,'C');
	$pdf->Cell(40,6,'Patente',1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','');
	$pdf->Cell(50,6,$datosfiscalizar->getTelefono_inmueble(),1,0,'C');
	$pdf->Cell(50,6,$datosfiscalizar->getRif(),1,0,'C');
	$pdf->Cell(50,6,'',1,0,'C');
	$pdf->Cell(40,6,$datosfiscalizar->getPatente(),1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	//$array_label=$datosfiscalizar->SolicitudObject->Espec_Tip_Dsctos();
	$pdf->Cell(25,6,'Actividad','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(92,6,'blablabla','TRB',0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(33,6,'Fecha de Inicio','LTRB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(40,6,$datosfiscalizar->getFec_inicio_ejerc(),1,0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(25,6,'Area Total:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(25,6,$datosfiscalizar->getArea_total(),'TRB',0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(23,6,'Area Util:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(27,6,$datosfiscalizar->getArea_util(),'TRB',0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(50,6,'Numero de Empleados:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(40,6,$datosfiscalizar->getNumero_empleado(),'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(50,6,'Facturacion del servicio:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(50,6,$datosfiscalizar->Tipo_facturacion->getIdTF(),'TRB',0,'L');
	$pdf->SetFont('','B');
	$pdf->Cell(40,6,'Municipio:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(50,6,$datosfiscalizar->parroquia->getId_municipio(),'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(20,6,'Medidor',1,0,'C');
	$pdf->Cell(62,6,'Numero de Cuenta Electrica',1,0,'C');
	$pdf->Cell(58,6,'Uso del Inmueble',1,0,'C');
	$pdf->Cell(50,6,'Tipo de recoleccion',1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','');
	$exist=($datosfiscalizar->getExist_medidor()=='1' && !is_null($datosfiscalizar->getExist_medidor()))?'Si':'No';
	$pdf->Cell(20,6,$exist,1,0,'C');
	$pdf->Cell(62,6,$datosfiscalizar->getNum_cta_electrica(),1,0,'C');
	$pdf->Cell(58,6,'Vivienda',1,0,'C');
	$pdf->Cell(50,6,$datosfiscalizar->Tipo_recoleccion->getId_Recol(),1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(26,6,'Supervisor:','LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(164,6,'Super','TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B',13);
	$pdf->Cell(190,6,'Datos de la Empresa Suministrados por',1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B',12);
	$pdf->Cell(40,6,"Nombre y Apellido:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(150,6,$datosfiscalizar->getApenom_suministra(),'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(14,6,"Cargo:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(176,6,$datosfiscalizar->getCargo_suministra(),'TRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(190,6,"Observaciones:",'LRT',1,'L');
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','');
	$pdf->Cell(190,6,$datosfiscalizar->getObservacion(),'LRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(190,6,"Resolucion:",'LRT',1,'L');
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','');
	$pdf->Cell(190,6,$datosfiscalizar->getResolucion(),'LRB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B',13);
	$pdf->Cell(190,6,'Informacion del Solicitante',1,0,'C');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B',12);
	$pdf->Cell(41,6,"Nombre y Apellido:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(149,6,$datosfiscalizar->Solicitud->solicitante->getNombre(),'RTB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(20,6,"Telefono:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(170,6,$datosfiscalizar->Solicitud->solicitante->getTelefono(),'RTB',0,'L');
	$pdf->Ln($new_line);
	$pdf->Cell($margen_izqu);
	$pdf->SetFont('','B');
	$pdf->Cell(15,6,"Motivo:",'LTB',0,'L');
	$pdf->SetFont('','');
	$pdf->Cell(175,6,$datosfiscalizar->Solicitud->getMotivo(),'RTB',0,'L');
	$pdf->Ln($new_line);
		}
}//End si orientacion es p
}//Si no esta seteado orientacion
$pdf->Output();
?>